### ISSUE TITLE
如何更新数据,

### ISSUE THREAD

**Issue by wodx521** [antvis/F2Native#34]
项目demo例子中全部都是本地json文件加载数据, 实际情况中都是通过网络加载数据, 首次设置数据后要进行数据更新, 没有对应的方法, 并且在之前文档找到说更新数据的方法 chart.repaint();  但是根本找不到对应的api

**Comment by weiqingtangx** [comment]
更新可以重新走一遍参数设置，render()的过程。

**Comment by zealjiang** [comment]
一刷新数据，程序就崩溃，官方的文档太简陋了
