### ISSUE TITLE
iOS 用 F2Native 会绘图 提示信息 怎么 去设置 就是动态的显示提示信息

### ISSUE THREAD

**Issue by sophiemarceau** [antvis/F2Native#5]
<img width="716" alt="截屏2020-12-23 上午11 41 28" src="https://user-images.githubusercontent.com/8053647/102956883-f4483480-4513-11eb-905f-dd04ef8d49f6.png">
类似这种的 拖动显示 我看demo里没有这方面的例子 使用文档里也没有这种的使用说明

**Comment by yangxlei** [comment]
你好， 这个功能正在补充中。目前已经实现完成， 在元旦过后会同步出来,  届时也会更新文档。谢谢

**Comment by sophiemarceau** [comment]
打扰 请问这个功能怎么使用 怎么调的文档 在哪 您更新了么 烦请告诉我在哪 谢谢
