### ISSUE TITLE
缺失 third_party/AntGraphic 

### ISSUE THREAD

**Issue by snice** [antvis/F2Native#6]
缺失 third_party/AntGraphic

**Comment by snice** [comment]
这个问题导致android无法编译，请解决，谢谢

**Comment by yangxlei** [comment]
抱歉， AntGraphic 是蚂蚁域内正在升级的 canvas 解决方案，暂时还不在开源范围。 gradle 配置针对两种模式做了修改，执行 
gradlew  :android:f2native:assembleStandalone 可以在标准模式下编译, 不会依赖到 AntGraphic。

**Comment by yangxlei** [comment]
![image](https://user-images.githubusercontent.com/3272155/105486541-9f056b80-5ce9-11eb-9b19-a8b0488f2fc2.png)
有任何问题可以加钉钉群咨询，谢谢

**Comment by weiqingtangx** [comment]
已解决
