### ISSUE TITLE
iOS集成报错

### ISSUE THREAD

**Issue by qianbingzhen** [antvis/F2Native#7]
iOS报错：
Showing Recent Errors Only
/Users/user/Downloads/F2Native-master/core/graphics/util/json.h:9:10: 'nlohmann/json.hpp' file not found

In file included from /Users/user/Downloads/F2Native-master/core/graphics/util/json.cpp:9:
/Users/user/Downloads/F2Native-master/core/graphics/util/json.h:9:10: fatal error: 'nlohmann/json.hpp' file not found
#include <nlohmann/json.hpp>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by yangxlei** [comment]
麻烦先确认下是否没有同步 submodule 仓库

**Comment by yangxlei** [comment]
![f2native答疑群](https://user-images.githubusercontent.com/3272155/106462319-e00f3400-64d0-11eb-8369-4b77125f6c79.jpg)
有任何问题可以加入钉钉群咨询，谢谢

**Comment by weiqingtangx** [comment]
已解决
